In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
np.absolute(-5)

5

In [4]:
#few imoportan function 

In [5]:
#array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
a.shape   #gives the dimensions of array

(4,)

In [8]:
#can also be done as
print(a.shape)

(4,)


In [9]:
#creating 2d array
b = np.array([[1,2,3,4],[5,6,7,8]])
b.shape

(2, 4)

In [10]:
#dot product
b.T
#the above is for transpose

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [11]:
np.dot(b,b.T)

array([[ 30,  70],
       [ 70, 174]])

In [12]:
#the question helps to get the arguments this function will accept.
np.random.randint?

In [13]:
#task: to generate random marks of 10 student ranging from 60-100 
np.random.randint(60,100,10)

array([99, 66, 92, 93, 69, 79, 95, 66, 90, 60])

In [14]:
#creating a 2d array of 5x5 60-100 are marks
matrix_a=np.random.randint(60,100,(5,5))
print(matrix_a)

[[81 69 66 85 90]
 [91 71 99 94 83]
 [67 83 75 65 79]
 [62 93 83 72 70]
 [77 66 96 98 61]]


In [15]:
s=np.max(matrix_a)
d=np.min(matrix_a)
print(s,d)

99 61


In [16]:
a=np.array([0,1,2,-8,6,8,6,10,6,6])
#to get the index of the element where the minimum element occurs 
np.argmin(a)

3

In [17]:
print(np.unique(a,return_counts=True))

#np.unique will display unique elemnts wtihout repetition of a and return_count will basically give u the number of time it occured in that array 

(array([-8,  0,  1,  2,  6,  8, 10]), array([1, 1, 1, 1, 4, 1, 1]))


In [19]:
b=np.unique(a,return_counts=True)
print(b[0],b[1])

[-8  0  1  2  6  8 10] [1 1 1 1 4 1 1]


In [21]:
#code to find number with the heighest frequency in an array
idx=np.argmax(b[1]) #index with heighest frequency
element=b[0][idx]  #will print the number from tuple 0 and element at idx position
print(element)

6


In [23]:
#slicing
matrix_a

array([[81, 69, 66, 85, 90],
       [91, 71, 99, 94, 83],
       [67, 83, 75, 65, 79],
       [62, 93, 83, 72, 70],
       [77, 66, 96, 98, 61]])

In [25]:
#hoe to get 83 75 93 83
matrix_a[2:5,1:3]    #slicing

array([[83, 75],
       [93, 83],
       [66, 96]])